package seia.vanillamagicaddon.core;

import java.util.Arrays;

import net.minecraftforge.fml.common.ModMetadata;

public class VanillaMagicAddonMetadata 
{
	public static ModMetadata preInit(ModMetadata modMetadata) 
	{
		modMetadata.modId = VanillaMagicAddon.MODID;
		modMetadata.name = VanillaMagicAddon.NAME;
		modMetadata.description = "Addon for VanillaMagic mod.";
		modMetadata.url = "https://github.com/Sejoslaw/VanillaMagicAddon";
		modMetadata.version = VanillaMagicAddon.VERSION;
		modMetadata.authorList = Arrays.asList("Seia");
		modMetadata.credits = "";
		modMetadata.autogenerated = false;
		return modMetadata;
	}
}